### PR TITLE
Added a test(barely moved the test coverage needle) to allow me to make a pull request to get

### PR DESCRIPTION
**Pull request by Thegaijin**
@emugaya

#### What does this PR do?
The project is an implementation of CRUD functionality, similar to the buckletlist app
The  user can sign up and sign in to create, update, delete categories and recipes​ ​of food recipes.
The main page of the web app is where users can sign up or sign in. On sign in it redirects to the categories page
On the categories page. This is where categories are created with the option to view what's inside the categories, edit, and delete which is where the app will redirect to after the user logs in. The view link redirects to the the ingredients page.
On the ingredients page you can enter the recipe name and items in the recipe with the options to view the items, edit or delete the recipe.

#### Where should the reviewer start?
The reviewer should start with the readme file and follow instructions to set up their virtual environment so as to run the app.

#### How should this be tested manually?
cd into the tests folder and run pytest -v from your terminal.
#### OR
Run this command in your terminal for a more comprehensive test coverage report.
pytest --cov-report term --cov=app

#### Questions?
Any suggestions of improvements I could make?
How can I get my test coverage to 100%? So far I've added 3 tests and I have only been able to get it to move from 53% to 55%. Please advise.
How do I get my maintainability score to an A?

### CODE REVIEW

**Comment by emugaya** [comment]
Hi Chief, You views are not being called during the tests. Refer to [this](http://flask.pocoo.org/docs/0.12/testing/) resource. it can help in reorganizing the tests. Secondly, split the tests into files according to functionality.

**Comment by Thegaijin** [comment]
@emugaya thanks for the resources.

**Comment by emugaya** [comment]
Have You started working on the API? I suggest you proceed to the API and complete all challenges before you join the fellowship. That will give you time to when you join.

**Comment by Thegaijin** [comment]
Cool, let me do that. Thanks for the heads up

**Pull request merged**
